# Numpy utils

In [21]:
salary = [159.3, 563.7, 578.1, 248.3]

scale = 1.05
# salary_upd = [round(el * scale, 2) for el in salary]
salary_upd = [el * scale for el in salary]
# salary_upd_rounded = map(round, salary_upd)
salary_upd_rounded = list(map(lambda x: round(x, 2), salary_upd))

# salary_upd = salary * scale
print(salary)
print(salary_upd)
print(salary_upd_rounded)


[159.3, 563.7, 578.1, 248.3]
[167.26500000000001, 591.8850000000001, 607.005, 260.71500000000003]
[167.27, 591.89, 607.0, 260.72]


In [22]:
import numpy as np

salary = [159.3 / 10000000, 563.7 / 10000000,
          578.1 / 10000000, 248.3 / 10000000] * 1

salary_as_np = np.array(salary)
# salary_as_np = np.fromiter(map(round, salary), dtype='float32')

print(type(salary_as_np))
# print(salary)
print(salary_as_np)

scale = 10000000.05
salary_upd = salary_as_np * scale
print(salary_upd)
print(np.round(salary_upd, 2))
print(list(np.round(salary_upd, 2)))



<class 'numpy.ndarray'>
[1.593e-05 5.637e-05 5.781e-05 2.483e-05]
[159.3000008  563.70000282 578.10000289 248.30000124]
[159.3 563.7 578.1 248.3]
[159.3, 563.7, 578.1, 248.3]


In [23]:
# salary = [159.3, 563.7, 578.1, 248.3]
# salary = [-159, 563, 578, 248]
salary = [159, 563, 578, 248]

# salary_as_np = np.array(salary)
# salary_as_np = np.array(salary, dtype='uint32')
# salary_as_np = np.array(salary, dtype='float32')
salary_as_np = np.array(salary, dtype=np.float32)
print(salary_as_np)
print(salary_as_np.shape)
print(salary_as_np.itemsize)
print(salary_as_np.dtype)




[159. 563. 578. 248.]
(4,)
4
float32


In [24]:
! pip install memory_profiler

In [25]:
import numpy as np
from memory_profiler import profile

NUMS = 10 ** 6


@profile
def list_case():
    nums = [num for num in range(NUMS)]
    print(type(nums), len(nums), nums[-1])


@profile
def np_case():
    nums = np.arange(NUMS)
    print(type(nums), len(nums), nums[-1], nums.dtype)


list_case()
np_case()

# if __name__ == "__main__":
#   list_case()
#   np_case()

ERROR: Could not find file <ipython-input-25-5b008c16f303>
NOTE: %mprun can only be used on functions defined in physical files, and not in the IPython environment.
<class 'list'> 1000000 999999
ERROR: Could not find file <ipython-input-25-5b008c16f303>
NOTE: %mprun can only be used on functions defined in physical files, and not in the IPython environment.
<class 'numpy.ndarray'> 1000000 999999 int64


In [26]:
salary = [579, 470, 193, 328, 478, 236, 697]
print(sorted(salary))
salary_as_np = np.array(salary)
print(salary_as_np.mean())
print(np.mean(salary_as_np))
print(np.median(salary_as_np))

percents = (1, 5, 10, 25, 50, 75, 95, 99)
# percents = (25, 50, 75)
salary_stat = np.percentile(salary_as_np, percents)
print(salary_stat)
print(dict(zip(percents, salary_stat)))


[193, 236, 328, 470, 478, 579, 697]
425.85714285714283
425.85714285714283
470.0
[195.58 205.9  218.8  282.   470.   528.5  661.6  689.92]
{1: 195.58, 5: 205.9, 10: 218.8, 25: 282.0, 50: 470.0, 75: 528.5, 95: 661.5999999999999, 99: 689.92}


In [27]:
nums = np.array([1, 2, 3, 4])
nums_2 = np.array([5, 6, 7, 8])
nums_sum = nums + nums_2
nums_sub = nums - nums_2
nums_mul = nums * nums_2
print(nums_sum)
print(nums_sub)
print(nums_mul)

nums_3 = np.append(nums, [9, 10])
print(nums_3)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 1  2  3  4  9 10]


In [28]:
nums = np.arange(1, 51)
# print(nums, nums.shape)
# prices = [1, 2, 3]
# print(prices[2:None])

# new_shape = (5, -1)
# nums_by_strict = nums.reshape(new_shape)
# print(nums_by_strict, nums_by_strict.shape)

# nums_by_ten = nums.reshape((-1, 10))
# nums_by_ten = nums.reshape((10, -1))
# print(nums_by_ten)
# print(nums_by_ten.sum())
# print(nums_by_ten.sum(axis=0))
# print(nums_by_ten.sum(axis=1))
# print(nums_by_ten.prod(axis=0))
# print(nums_by_ten.prod(axis=1))

nums_3d = nums.reshape((-1, 5, 2))
print(nums_3d)
print(nums_3d.shape)
print(nums_3d[0, 0, 0])
print(nums_3d[:, 0, 0])
print(nums_3d[:, :, 0])



[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]

 [[21 22]
  [23 24]
  [25 26]
  [27 28]
  [29 30]]

 [[31 32]
  [33 34]
  [35 36]
  [37 38]
  [39 40]]

 [[41 42]
  [43 44]
  [45 46]
  [47 48]
  [49 50]]]
(5, 5, 2)
1
[ 1 11 21 31 41]
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]


In [29]:
nums = np.arange(1, 101, dtype=np.int32)

nums_by_ten = nums.reshape((-1, 10))
print(nums_by_ten)
print(np.linalg.det(nums_by_ten))
nums_by_ten_t = nums_by_ten.transpose()
print(nums_by_ten_t)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
-2.3389671972701e-111
[[  1  11  21  31  41  51  61  71  81  91]
 [  2  12  22  32  42  52  62  72  82  92]
 [  3  13  23  33  43  53  63  73  83  93]
 [  4  14  24  34  44  54  64  74  84  94]
 [  5  15  25  35  45  55  65  75  85  95]
 [  6  16  26  36  46  56  66  76  86  96]
 [  7  17  27  37  47  57  67  77  87  97]
 [  8  18  28  38  48  58  68  78  88  98]
 [  9  19  29  39  49  59  69  79  89  99]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [30]:
nums = np.arange(1, 21)
nums_by_ten = nums.reshape((-1, 2, 10))
print(nums_by_ten)
nums_flat = nums_by_ten.reshape(-1)
print(nums_flat)
nums = np.arange(1, 10.4736842, 0.47368421)
print(len(nums), nums)
#
nums_2 = np.linspace(1, 10, 9)
print(len(nums_2), nums_2)


def my_f(x, y):
    # print(x.dtype)
    return x ** 2 + y + 1


# x = np.linspace(1, 10, 10)
# y = np.linspace(1, 5, 10)
z = np.fromfunction(my_f, (10, 5))
print(my_f(9, 4))
print(z)

# e_arr = np.empty((4, 5))
# e_arr = np.empty((4, 5), dtype=np.uint16)
e_arr = np.zeros((4, 5), dtype=np.uint16)
print(e_arr, e_arr.dtype)


[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
20 [1.         1.47368421 1.94736842 2.42105263 2.89473684 3.36842105
 3.84210526 4.31578947 4.78947368 5.26315789 5.7368421  6.21052631
 6.68421052 7.15789473 7.63157894 8.10526315 8.57894736 9.05263157
 9.52631578 9.99999999]
9 [ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]
86
[[ 1.  2.  3.  4.  5.]
 [ 2.  3.  4.  5.  6.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [17. 18. 19. 20. 21.]
 [26. 27. 28. 29. 30.]
 [37. 38. 39. 40. 41.]
 [50. 51. 52. 53. 54.]
 [65. 66. 67. 68. 69.]
 [82. 83. 84. 85. 86.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] uint16


In [31]:
nums = np.arange(1, 21)
print(nums)
# lighten = np.where(pict[0, :, :] > 250)
idx_1 = nums > 10
print(idx_1, type(idx_1), idx_1.dtype)
nums_1 = nums[idx_1]
print(nums_1)
print(nums[nums > 10])
print(nums[nums ** 2 > 10])
print(nums.cumsum())
print(np.diff(nums))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True] <class 'numpy.ndarray'> bool
[11 12 13 14 15 16 17 18 19 20]
[11 12 13 14 15 16 17 18 19 20]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
